#!/bin/sh
# Script to unload aesdchar driver

# Remove the module
module="aesdchar"
device="aesdchar"

# Remove the device if it exists
if [ -e /dev/${device} ]; then
    rm -f /dev/${device}
fi

# Unload the module
if lsmod | grep "$module" &> /dev/null ; then
    rmmod $module
fi
