#!/bin/sh
# Script to load aesdchar driver
module="aesdchar"
device="aesdchar"
mode="664"
group="sudo"

# Remove any existing device
if [ -e /dev/${device} ]; then
    rm /dev/${device}
fi

# Remove the module if already loaded
if lsmod | grep "$module" &> /dev/null ; then
    rmmod $module
fi

# Load the module
insmod ./$module.ko || exit 1

# Retrieve the major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Create the device node
mknod /dev/${device} c $major 0

# Set permissions
chgrp $group /dev/${device}
chmod $mode /dev/${device}
